### ISSUE TITLE
Πρόβλημα στην εγκατάσταση του MIT App Inventor

### ISSUE THREAD

**Issue by psmpiliri** [courses-ionio/sw#17]
Εγκατέστησα το MIT App Inventor στον υπολογιστή μου όμως το κινητό δεν μου δίνει την επιλογή να το συνδέσω ως 'mass storage device' στον υπολογιστή (όπως ζητείται στις οδηγίες) παρά μόνο ως συσκευή πολυμέσων... τι μπορώ να κάνω γι αυτό;

**Comment by midmandy** [comment]
Συνήθως το app inventor δουλεύει online με χρήση wifi και αυτό μάλλον είναι το πιο απλό. Αν θες να το συνδέσεις με USB δες τις οδηγίες που υπάρχουν εδώ: http://appinventor.mit.edu/explore/content/setup-device-usb.html
