### ISSUE TITLE
Απορία για επιλογή θέματος

### ISSUE THREAD

**Issue by maaggeld** [courses-ionio/sw#18]
Σχετικά με την δημιουργία εκπαιδευτικού παιχνιδιού με κάποιο άλλο εργαλείο και όχι με το scratch, εκτός από το HTML που έχει στο UDACITY μπορώ να κάνω Android? Ευχαριστω!

**Comment by midmandy** [comment]
Σύμφωνα και με την εκφώνηση το παιχνίδι που θα σχεδιάσεις/δημιουργήσεις "μπορεί να κατασκευαστεί με ένα εργαλείο περισσότερο προχωρημένο από το Scratch"
Μπορείς να δουλέψεις και σε Android αν θες, απλά φρόντισε να τηρήσεις τις προδιαγραφές της εργασίας του εκπαιδευτικού παιχνιδιού όπως αυτές ορίζονται στα projects.
