### ISSUE TITLE
Δεν με αφήνει να κάνω push

### ISSUE THREAD

**Issue by ThomasSps** [courses-ionio/sw#7]
αφού κάνω τι αλλαγές δεν με αφήνει να κάνω push την ενημερωμένη έκδοση μου, το παρακάτω error εμφανίζεται:

remote: Permission to courses-ionio/sw.git denied to thomassps.
fatal: unable to access 'https://github.com/courses-ionio/sw.git/': The requested URL returned error: 403

**Comment by midmandy** [comment]
Αυτό συμβαίνει γιατί δεν έχεις ακόμα πρόσβαση στο repository του μαθήματος.

Σε έχω καλέσει όταν μου έστειλες το username σου αλλά μου δείχνει εδώ ότι το invite είναι pending... που σημαίνει ότι εκκρεμεί, άρα πρέπει να κάνεις accept στο invitation που σου έστειλα για να αποκτήσεις πρόσβαση.

**Comment by ThomasSps** [comment]
ω ναι σωστά, ευχαριστώ πολυ :)

**Comment by Gkakav2** [comment]
Μπορεί κάποιος να μου πει αν είναι σωστό αυτό που έκανα; είμαι ο Π2012047

2015-03-01 1:04 GMT+02:00 Thomas Henry Spiteri <notifications@github.com>:

**Comment by ThomasSps** [comment]
μια χαρα φαινεται :)

**Comment by Gkakav2** [comment]
ναι εννοώ επειδή δεν έχω κάνει φάκελο έχω κάνει μόνο αρχείο αν παρατηρήσεις!

2015-03-01 19:00 GMT+02:00 Thomas Henry Spiteri <notifications@github.com>:

**Comment by midmandy** [comment]
Όπως συμπλήρωσα και στις οδηγίες, είναι λάθος να δημιουγείτε αρχεία έξω από το φάκελό σας γιατί έτσι θα είναι δύσκολη η τακτοποίησή τους και η συντήρηση του repository. Κάποιοι φακέλοι δημιουργήθηκαν και διορθώθηκαν τυχόν λάθη. Έχει προστεθεί κι ένα tutorial αν χρειαστείτε βοήθεια.

**Comment by ThomasSps** [comment]
εγω βλεπω εναν φακελο 047 :/

**Comment by Gkakav2** [comment]
Ναι ναι μου τον εφτιαξαν! Ευχαριστώ πάντως
