### ISSUE TITLE
Απορίες

### ISSUE THREAD

**Issue by epidrome** [courses-ionio/sw#829]
Σε αυτήν την περιοχή μπορείτε να στέλνετε γενικές απορίες σχετικά με το μάθημα.

Αν το ερώτημα σχετίζεται με μια συγκεκριμένη εργασία θα πρέπει να το στείλετε στα θέματα στο αντίστοιχο αποθετήριο της εργασίας.

[Οδηγίες για την χρήση των issues-notifications](https://guides.github.com/features/issues/)

**Comment by p15avge** [comment]
Καλησπέρα,

Εφόσον είμαι χρήστης ubuntu οι εργασίες θα πρέπει να γίνουν σε καθαρό installation ; 

Επίσης τι αρκιβώς πρέπει να καταγράψουμε με το asciinema, μόνο τις εντολές και το τελικό αποτέλεσμα ή και το installation ;

Ευχαριστώ πολύ

**Comment by mkamgit** [comment]
Δεν υπάρχει εξαίρεση για κάποιο λειτουργικό σύστημα.
["Η εγκατάσταση εργαλείων προγραμματισμού θα πρέπει να γίνεται σε καθαρό λειτουργικό σύστημα, χωρίς άλλα προγράμματα..."](https://courses-ionio.github.io/help/faq/)


Δεν χρειάζεται να καταγραφεί κάποιο installation εκτός αν αναφέρεται διαφορετικά στην άσκηση. 
[π.χ. "install and configure in a user folder a python project that is not available through the package manager"](https://github.com/courses-ionio/dokey)

**Comment by p17kagk** [comment]
Καλησπέρα,

Θα ήθελα να ρωτήσω τα εξής:

Α) Στις ασκήσεις 1) "try different operating systems in the emulator" 2) "configure a custom window manager" και 3) "send notifications to your desktop-mobile", θέλετε το αποτέλεσμα να καταγραφεί στο asciinema, ή μόνο τις εντολές εγκατάστασης/εκτέλεσης?

Β) Στην άσκηση "try different terminals and shells", αντιμετώπισα τα εξής προβλήματα: 1) Όταν καλείς τον st, αυτό ανοίγει σε νέο παράθυρο. Εκεί η καταγραφή του asciinema σταματά. Είναι αποδεκτό να κάνω δεύτερη καταγραφή μέσα απο το παράθυρο του st, και στην συνέχεια να κάνω asciinema play απο το αρχικό μου παράθυρο? 2) Επίσης κάποιες ειδικές λειτουργίες όπως χρώματα ή zoom in/zoom out δεν μπορούν να καταγραφούν στο asciinema. Θέλετε να σας τις παρουσιάσουμε με κάποιον άλλο τρόπο (πχ screenshot)?

Ευχαριστώ,
Ανδρέας Καγκελάρης
Π2017203
p17kagk@ionio.gr

**Comment by mkamgit** [comment]
Γενικά θέλουμε **να χρησιμοποιηθεί το εργαλείο asciinema**. Ωστόσο, επειδή προέχει η **τεκμηρίωση των ενεργειών και των αποτελεσμάτων** των ασκήσεων, είναι αποδεκτή η χρήση ενδεικτικών οθονών (πχ screenshot) ή/και animated GIF μόνο για τα στάδια των ασκήσεων που **δεν είναι δυνατή** η καταγραφή μέσω του εργαλέιου asciinema.

**Comment by p17gera** [comment]
mibook/gr#55
Γι αυτο το bug τι πρέπει να κάνουμε για να προχωρίσουμε την εργασία στο [συμμετοχικό εκπαιδευτικό υλικό](https://github.com/courses-ionio/projects/blob/master/social/index.md) ;

**Comment by epidrome** [comment]
οι λύσεις περιγράφονται αναλυτικά στο λινκ που λέτε και έχουν συζητηθεί ήδη 2-3 φορές στο μάθημα

**Comment by gmargaritis** [comment]
Καλησπέρα,
Για να δω αν έχω καταλάβει σωστά, σχετικά με το παραδοτέο στις 30 Μαρτίου, πρέπει να παραδώσουμε όσες από τις πρώτες 5  ασκήσεις έχουμε επιλέξει να κάνουμε?

**Comment by mkamgit** [comment]
Ναι, θέλουμε 5 ασκήσεις, όποιες επιλέξετε από την ενότητα software.

Προσέξτε ότι για να θεωρηθούν εμπρόθεσμες πρέπει εντός της προθεσμίας να κάνετε **commit** το σχετικό περιεχόμενο στην αναφορά σας.
**Σύμφωνα με τις οδηγίες δεν πρέπει να κάνετε ακόμα pull request στο κεντρικό αποθετήριο του μαθήματος.**

**Comment by mmits** [comment]
Το σημερινό εργαστήριο θα γίνει σήμερα;

**Comment by epidrome** [comment]
@mmits 
https://github.com/courses-ionio/sw-lab/issues/1

**Comment by p17kagk** [comment]
Καλησπέρα, μια ερώτηση.
έστω οτι έχουμε κάνεις τις 6 ασκήσεις.
έχει νόημα να προσθέσουμε 7η, 8η κτλ άσκηση μετά τις 10/05 που είναι η τελική ημερομηνία υποβολής των ασκήσεων?

ευχαριστώ,
Ανδρέας

**Comment by mkamgit** [comment]
@p17kagk Όχι.

**Comment by p15avge** [comment]
Η προθεσμία για την παράδωση της τελικής αναφοράς είναι ίδια με την προθεσμία για την παράδωση των ασκήσεων ;

**Comment by epidrome** [comment]
@mkamgit @p17kagk 

1. σύμφωνα με τις οδηγίες έχει νόημα γιατί θα μετρήσει ο βαθμός από τις καλύτερες 

2. επιπλέον, οι εξετάσεις φαίνεται πως δεν θα γίνουν και στην θέση τους **μάλλον** θα μπουν εργασίες

**Comment by mkamgit** [comment]
@epidrome  @p17kagk Απλά πρέπει να γίνει κατανοητό ότι οι επιπλέον ασκήσεις **μετά τις 10/05**, όπως αναφέρεις στο ερώτημά σου, θεωρούνται εκπρόσθεσμες και συνεπώς έχουν ποινή στη βαθμολόγησή τους. Οπότε έχει νόημα σε ειδικές περιπτώσεις (κακή εμπρόθεσμη και άριστη εκπρόθεσμη).

@p15avge Όχι, οι προθεσμίες είναι διαφορετικές και αναφέρονται στις οδηγίες.

**Comment by epidrome** [comment]
@mkamgit @gmargaritis 

> Ναι, θέλουμε 5 ασκήσεις, όποιες επιλέξετε από την ενότητα software.

Οχι θέλουμε 3 ασκήσεις από τις πρώτες 5 της λίστας

**Comment by gmargaritis** [comment]
@epidrome 
> @mkamgit @gmargaritis
> 
> > Ναι, θέλουμε 5 ασκήσεις, όποιες επιλέξετε από την ενότητα software.
> 
> Οχι θέλουμε τις μισές (=3) ασκήσεις του μαθήματος από τις πρώτες 5 της λίστας

Καλησπέρα, εγώ όπως και πολλοί άλλοι συνάδελφοι, έδρασα σύμφωνα με την παραπάνω οδηγία που δόθηκε στις 29 Μαρτίου. Θα έχει αυτό κάποιο αρνητικό αντίκτυπο την τελική βαθμολογία ;

**Comment by epidrome** [comment]
περισσότερες ασκήσεις, νωρίτερα, και μάλιστα αυξημένης δυσκολίας μόνο θετικό είναι!

**Comment by chriskotrotsios** [comment]
Καλησπέρα , έχω μια ερώτηση σχετικά με τις πρόσθετες εργασίες αντί για τελική εξέταση. Η "Μια άσκηση γραμμής εντολών" μπορεί να είναι οποιαδήποτε ή θα είναι απο την 6+; Επιπλέον, έχει κάποια προθεσμία, η έιναι η ίδια με την προθεσμία της τελικής αναφοράς (δηλ. 1 Ιουνίου);

**Comment by epidrome** [comment]
1. όποια άσκηση θέλετε

2. παράδοση μαζί με την τελική αναφορά, δλδ 1η Ιουνίου

**Comment by dmisa** [comment]
Καλησπέρα, για την "Μια εργασία συμμετοχικού περιεχομένου από τα Β, Γ (10%)" μπορούμε να κάνουμε μια εργασία τύπου Β ενώ έχουμε ξανακάνει μια  εργασία Β ή πρέπει αναγκαστικά να επιλέξουμε να κάνουμε την εργασία Γ;

**Comment by p15avge** [comment]
Καλησπέρα, θα ήθελα να κάνω και εγώ μία ερώτηση, σχετικά με τη βαθμολόγηση μιας και άλλαξαν τα δεδομένα. Οι 2 επιπλέον ασκήσεις θα βαθμολογηθούν ξεχωριστά από το υπόλοιπο σύνολο (απαιτώντας 50% επιτυχία) ή θα διαμορφωθεί η βαθμολογία σε 70% ασκήσεις και 30% συμμετοχικό ;

**Comment by epidrome** [comment]
@dmisa μπορείτε να διαλέξετε ότι θέλετε

@p15avge αφού χάσαμε την γραπτή εξέταση η απαίτηση για βάση μεταφέρεται στις ασκήσεις, στο συμμετοχικό υπήρχε ήδη απαίτηση για βάση.

**Comment by chriskotrotsios** [comment]
Καλησπέρα, έχω κάνει pull request εδώ και 8-9 μέρες και έχει γίνει flagged ως Overdue και έχει το μήνυμα "Λυπάμαι, αλλά το αίτημα σας έχει καταχωρηθεί ως εκπρόθεσμο και ένα ρομπότ θα το κλείσει οριστικά σε μερικές μέρες.". Θα χρειαστεί να ξανακάνω pull request?

**Comment by mkamgit** [comment]
@chriskotrotsios @dmisa Όχι, Τα αιτήματά σας είναι εμπρόθεσμα, θα διευθετηθούν τις επόμενες ημέρες και δεν απαιτείται κάποια περαιτέρω ενέργεια από εσάς.

**Comment by dmisa** [comment]
Καλημέρα, από την στιγμή που το μάθημα γίνεται με απαλλακτικές εργασίες εμείς θα πρέπει να το δηλώσουμε στην πλατφόρμα exams.ionio.gr;

**Comment by epidrome** [comment]
το μάθημα-αξιολόγηση μας έχει ήδη ολοκληρωθεί και είμαστε στην φάση της τελικής βαθμολόγησης, δεν βλέπω σε τι βοηθάει η δήλωση στην νέα πλατφόρμα.

**Comment by lextale** [comment]
Οι τελικές βαθμολογήσεις έχουν ολοκληρωθεί; Δεν έχω λάβει ακόμα βαθμό.

**Comment by epidrome** [comment]
@lextale ναι η βαθμολόγηση έχει γίνει

παρατηρώ ότι η δική σου αναφορά δεν έχει σταλεί στο κεντρικό 

οπότε, δεν βαθμολογήθηκε

πάντως, παρατηρώ ότι δεν έχουν γίνει όλες οι ασκήσεις, 

οπότε πριν την στείλεις τον Σεπτ καλό θα ήταν να μελετήσεις πιο προσεκτικά τις οδηγίες 

ή, ιδανικά, να πάρεις το μάθημα πάλι και να παρουσιάσεις τις ασκήσεις στην τάξη

καθώς αυτός είναι ο βασικός λόγος που οι περισσότεροι κόβονται ή/και δεν έχουν καλό βαθμό

**Comment by p17laso** [comment]
Γεια σας, η βαθμολογία δεν έχει αναρτηθεί ούτε σε εμένα και από ότι είδα το pull request μου έγινε merged. Γίνεται να βαθμολογηθώ τώρα και να μην ξαναστείλω την αναφορά τον Σεπτέμβρη;

**Comment by epidrome** [comment]
@p17laso 
πράγματι θα έπρεπε να περάσεις,
μάλλον έχει γίνει κάποιο λάθος, 
θα σου απαντήσει ο @c15pati 
που έκανε την ενσωμάτωση-βαθμολόγηση
https://github.com/courses-ionio/sw/pull/878

**Comment by p17laso** [comment]
> @p17laso
> πράγματι θα έπρεπε να περάσεις,
> μάλλον έχει γίνει κάποιο λάθος,
> θα σου απαντήσει ο @c15pati
> που έκανε την ενσωμάτωση-βαθμολόγηση
> #878

Έγινε ευχαριστώ!

**Comment by c15pati** [comment]
> Γεια σας, η βαθμολογία δεν έχει αναρτηθεί ούτε σε εμένα και από ότι είδα το pull request μου έγινε merged. Γίνεται να βαθμολογηθώ τώρα και να μην ξαναστείλω την αναφορά τον Σεπτέμβρη;

@epidrome , @p17laso ανέβηκε και η βαθμολογία, συγγνώμη για την καθυστέρηση, κάπου είχε παραπέσει το Pull request.

**Comment by lextale** [comment]
Μα την αναφορά μου την είχα στείλει. Δεν μπορώ να καταλάβω τι πήγε λάθος.

**Comment by mkamgit** [comment]
@lextale https://github.com/courses-ionio/sw/pull/850#issuecomment-640004176

**Comment by p17laso** [comment]
> > Γεια σας, η βαθμολογία δεν έχει αναρτηθεί ούτε σε εμένα και από ότι είδα το pull request μου έγινε merged. Γίνεται να βαθμολογηθώ τώρα και να μην ξαναστείλω την αναφορά τον Σεπτέμβρη;
> 
> @epidrome , @p17laso ανέβηκε και η βαθμολογία, συγγνώμη για την καθυστέρηση, κάπου είχε παραπέσει το Pull request.

Γεια σας, συγγνώμη για την ενόχληση πάλι, αλλά μπαίνω gram-web εδώ και τρεις μέρες για να τσεκάρω μπας και κάπου έχει κολλήσει και δε μου βγάζει βαθμολογία και ακόμα δεν έχει αναρτηθεί ο βαθμός.

**Comment by epidrome** [comment]
το ιόνιο είχε βλάβη στο δίκτυο, μάλλον σήμερα θα φανεί

**Comment by lazarospapanikolaou** [comment]
καλησπερα. Στην εξεταση του σεπτεμβριου υπαρχει η δυνατοτητα να γινει με απαλλακτικες εργασιες οπως του ιονιου;

**Comment by epidrome** [comment]
@lazarospapanikolaou #835

**Comment by p17nouv** [comment]
Καλησπέρα, όσοι δεν εχουμε στειλει τις εργασίες για την εξεταστική του ιουνίου, μπορούμε να στειλουμε τις εργασίες που αναφέρατε για την επναληπτική εξέταση του Σεπτεμβρίου ή έπρεπε να είχαμε στειλει και τις προηγούμενες εργασίες;

**Comment by mkamgit** [comment]
@p17nouv Οι πρόσθετες εργασίες υποκαθιστούν μόνο την **[επαναληπτική εξέταση του Σεπτεμβρίου](https://github.com/courses-ionio/sw/issues/835)**. Από εκεί και πέρα ισχύουν οι οδηγίες του μαθήματος για την τελική βαθμολογία.

**Comment by leuteris99** [comment]
Καλημερα, εγώ παρότι εχει γινει merge η εργασια μου δεν εχω παρει βαθμο. Ειναι πολυ αργα τωρα? Μπορώ να την ξαναστειλω τον Σεπτέμβρη?

**Comment by c15pati** [comment]
@leuteris99 Καλησπέρα όσον αφορά την εργασία σου λόγω λάθος δικού μου, καθυστέρησε η βαθμολόγησή της. Δεν χρειάζεται να την ξαναστείλεις για τον Σεπτέμβρη.

**Comment by leuteris99** [comment]
> Καλημερα, εγώ παρότι εχει γινει merge η εργασια μου δεν εχω παρει βαθμο. Ειναι πολυ αργα τωρα? Μπορώ να την ξαναστειλω τον Σεπτέμβρη?

Σχετικά με την βαθμολογηση μου θα ήθελα να ρωτισω σε ποιο στάδιο βρισκεται επειδή εχουν περασει μερικές ημέρες απο την απαντηση σας.

**Comment by lazarospapanikolaou** [comment]
καλησπερα
Σας εχει σταλθει το pull request που εχω κανει ;

**Comment by epidrome** [comment]
@lazarospapanikolaou 
https://github.com/courses-ionio/sw/pulls

**Comment by lextale** [comment]
Καλησπέρα,
Το pull request μου δεν έγινε δεκτό όπως την τελευταία φορά. Έχω διαβάσει και έχω ακολουθήσει τις οδηγίες και ακόμα δεν μπορώ να καταλάβω γιατί συμβαίνει αυτό και τι παραλείπω. Παρακαλώ θα ήθελα να μου λύσετε την απορία. Επίσης, εάν μπορέσω να το διορθώσω μπορώ να ξανακάνω το pull request και να γίνει δεκτό;

**Comment by epidrome** [comment]
@lextale το πρόβλημα του αιτήματος σου έχουν σχολιαστεί με σαφήνεια εκεί:
https://github.com/courses-ionio/sw/pull/907#issuecomment-694672228

**Comment by p13brif** [comment]
Καλησπέρα , 
Είμαι επί πτυχίω φοιτητής και ήθελα να ρωτήσω αν μπορούν να μου ανατεθούν εργασίες στο τρέχον εξάμηνο για να βαθμολογηθώ. Ευχαριστώ

**Comment by epidrome** [comment]
@p13brif 
https://courses-ionio.github.io/help/faq/

**Comment by lextale** [comment]
Καλημέρα, ήθελα να ρωτήσω αν έχουν περαστεί οι βαθμολογίες για το μάθημα, γιατί είναι το μόνο από την εξεταστική Σεπτεμβρίου που δεν έχω λάβει βαθμό.
Ευχαριστώ.

**Comment by epidrome** [comment]
πράγματι δεν φαίνεται να έχουν βαθμολογηθεί οι εργασίες σου από τον @c15pati

**Comment by c15pati** [comment]
Added the grade

**Comment by babismacheras** [comment]
Γειά σας! είμαι επί πτυχίω φοιτητής κα σύμφωνα με την απόφαση της περασμένης εβδομάδας πληρώ τα κριτήρια για εξέταση εαρινών μαθημάτων κατά την προσεχή εξεταστική.  θα ήθελα να μάθω α)εάν οι εργασίες είναι οι ίδιες με αυτές της περασμένης εξεταστικής ή εάν θα ανακοινωθούν νέες και β) εάν η ημερομηνία παράδοσης είναι αυτή που θα ανακοινωθεί ως ημερομηνία εξέτασης στο πρόγραμμα της εξεταστικής. Ευχαριστώ για το χρόνο σας!

**Comment by epidrome** [comment]
ναι, ισχύει ότι βλέπεις στην σελίδα και τα λινκ με προθεσμία αποστολής πουλ ρικουεστ την ημέρα εξέτασης
https://github.com/courses-ionio/sw
