### ISSUE TITLE
Απορίες

### ISSUE THREAD

**Issue by c15pati** [courses-ionio/sw#915]
Σε αυτήν την περιοχή μπορείτε να στέλνετε **γενικές απορίες** σχετικά με το μάθημα.

**Αν το ερώτημα σχετίζεται με μια συγκεκριμένη εργασία θα πρέπει να το στείλετε στα θέματα στο αντίστοιχο αποθετήριο της εργασίας.**

[Οδηγίες για την χρήση των issues-notifications](https://guides.github.com/features/issues/)

**Comment by Haki-Malai** [comment]
Τι έγινε, πως θα συνεχιστεί το μάθημα;

**Comment by Haki-Malai** [comment]
Καλημέρα, εχθές είχα πρόβλημα με την κατάθεση της απάντησης μου. Εννοώ ότι ενώ πάτησα το κουμπί τίποτα δεν συνέβη. Είναι λογικό αυτό;

**Comment by p16andr** [comment]
Καλησπερα σας κυριε Πατηνιωτη μπορουμε να κανουμε μια προσωπικη συναντηση γιατι εχω πολλες αποριες σχετικα με το mIRC το tmate και το 1ο παραδοτεο για το βιογραφικο;;;

**Comment by epidrome** [comment]
@p16andr κάντε μια 1η προσπάθεια για αυτήν την εβδομάδα και θα το δούμε λίγο μαζί την Δευτ στο μάθημα, επίσης στο φροντιστήριο της επόμενης πέμπτης θα δούμε πάλι τα νέα εργαλεία και παράλληλα θα ήταν χρήσιμο να το προσπαθείσετε μόνοι σας καθώς και μεταξύ σας, 

όλες οι προσπάθειες μετράνε, ακόμη και οι αποτυχημένες, αρκεί να βελτιώνονται μετά τον σχολιασμό, μην αγχώνεστε!

η δικτυακή φύση του μαθήματος επιτρέπει, αν όχι επιβάλει, μια δικτυακή σχέση μεταξύ μας, όλοι με όλους σαν κόμβοι, όχι ο καθηγητής-βοηθός σαν μοναδικός κόμβος με ότι αυτό συνεπάγεται σε φόρτο

@c15pati αν θες βάλε λίγες ώρες γραφείου την ώρα του μαθήματος Δευτ-Πεμ οπότε όποιος θέλει να μπαίνει σε δικό σου ζουμ για βοήθεια ειδικά αν έχει μείνει πίσω

**Comment by akontinis** [comment]
[Εδω](https://courses-ionio.github.io/projects/bonus/) αναφερεται οτι ειναι για μπονους βαθμο
![image](https://user-images.githubusercontent.com/29643887/109364157-d93ccc80-7896-11eb-87b6-1cd506eb08af.png)
ενω [εδω](https://github.com/courses-ionio/sw) πιανει το 20% τι ισχυει τελικα;
![image](https://user-images.githubusercontent.com/29643887/109364377-5700d800-7897-11eb-9ef3-7699becb6fc1.png)

**Comment by epidrome** [comment]
@akontinis nice catch, fixed, thanks!

**Comment by p15bako** [comment]
Καλησπέρα, θέλω να κάνω μια ερώτηση σχετικά με το βίντεο κουίζ αυτής της εβδομάδας. Κάθισα να κάνω το βίντεο κουίζ αλλά μου βγάζει το εξής μήνυμα. "Please make sure that you are on the current week and sign in by selecting the user menu. Sometimes multiple reloads are needed, still looking for this bug...". Έχω κάνει κανονικά sign in και είμαι και στην τωρινή εβδομάδα. Όσα refresh και να κάνω το πρόβλημα επιμένει. Τι μπορώ να κάνω για να μην χάσω την εβδομάδα; Ευχαριστώ.

**Comment by epidrome** [comment]
@p15bako 
για δοκίμασε πάλι, αν επιμένει πάντως, υπάρχει και πλανΒ
https://github.com/courses-ionio/sw/issues/916#issuecomment-779342912

**Comment by p16andr** [comment]
@c15pati  @epidrome 
Καλησπέρα, εχω μια απορια οσον αφορα την διαδικασια με το CMS. Εχω αλλαξει τα settings μου και στο αποθετηριο με το config.yml αρχείο και τα Netlify settings. Δεν θα πρεπει να με κανετε invite τωρα για να μπορεσω να μπω στην σελίδα admin του sitegr;;;

**Comment by epidrome** [comment]
@p16andr 
> Αν το ερώτημα σχετίζεται με μια συγκεκριμένη εργασία θα πρέπει να το στείλετε στα θέματα στο αντίστοιχο αποθετήριο της εργασίας.

**Comment by p15bako** [comment]
Καλησπέρα, θέλω να κάνω μια ερώτηση σχετικά με τις απαντήσεις των βίντεο κουίζ πάνω στην αναφορά. Επειδή αντιμετώπισα και αυτή την εβδομάδα το bug, αποφάσισα να γράψω τις απαντήσεις μου πάνω στην αναφορά όπως υπέδειξε ο κ. Χωριανόπουλος. Όμως, όταν βάζω τις απαντήσεις μου, μου χαλάει τα links από το πινακάκι προς τις σχετικές αναφορές παρακάτω. Τι μπορώ να κάνω για αυτό;

**Comment by Miltos9** [comment]
καλησπέρα, σήμερα Κυριακή επιχείρησα να κάνω το video quiz και δεν μου επιτρέπει.Έχει καταχωρηθεί όπως τα υπόλοιπα που εχουν μπει σε dead line.Έχω να προτείνω ως deadline να βάζετε την Δευτέρα και όχι την Κυριακή(που θα έπρεπε να είναι εντός προθεσμίας).Αυτή την εβδομάδα εκτατός θα βάλω τις απαντήσεις στην αναφορά μου.

**Comment by dimpram** [comment]
Καλησπέρα, θέλω να σιγουρέψω αν ο τρόπος με τον οποίο κάνω την συνεισφορά μου στην σελίδα είναι έγκυρος. Πιο συγκεκριμένα, άνοιξα ένα [issue](https://github.com/ioniodi/sitegr/issues/109) στο sitegr που αφορά το αποθετήριο minimal-ionio οπότε το [PR](https://github.com/ioniodi/minimal-ionio/pull/39) μου βρίσκεται εκεί. Αυτό σημαίνει οτι το issue με το PR δεν μπορούν να επικοινωνίσουν και να κάνει close το issue αυτόματα κατά την ενσωμάτωση του PR μου. Υπάρχει πρόβλημα με αυτό; Θα έπρεπε να είχα ανοίξει το αντίστοιχο issue και στο minimal-ionio;

**Comment by p16andr** [comment]
@epidrome @c15pati 
Καλησπερα σας, ηθελα να σας ρωτησω αν εχετε απενεργοποιησει τις προσωπικες συναντησεις για τις αποριες με τον κυριο Πατηνιωτη επειδη εχω καποιες σημαντικες αποριες και οταν μπαινω στο calendly να κλεισω μια συναντηση μου λεει "No times in March";;;

**Comment by c15pati** [comment]
@p16andr Οι συναντήσεις ήταν (σε πρώτη φάση) μόνο για απαντήσεις σχετικά με τα καινούργια εργαλεία. Θα ξαναγίνουν, απλά όχι αυτή την εβδομάδα. Είχες κάποιο πρόβλημα να συνδεθείς, ή θέλεις να ρωτήσεις κάτι σχετικό με το μάθημα;

**Comment by Miltos9** [comment]
@epidrome @c15pati 
καλησπέρα, Όσοι έχουμε κάνει το συμμετοχικό περιεχόμενο το προηγούμενο εξάμηνο πως θα χειριστούμε την διαδικασία σε αυτό το εξάμηνο ? Θέλετε να την κάνουμε εκ νέου ή να βάλουμε ότι είχαμε κάνει στο  HCI ?

**Comment by epidrome** [comment]
@Miltos9 

αντιγραφή από τις οδηγίες:

> Η απλή προσθήκη περιεχομένου δεν σημαίνει ότι θα γίνει και κατοχύρωση του αντίστοιχου βαθμού αυτόματα, αφού θα πρέπει το υλικό που θα προσθέσετε να είναι σχετικό με το αντίστοιχο μάθημα (π.χ., στο μάθημα Τεχνολογία Λογισμικού μας ενδιαφέρει το λογισμικό ή/και η κατασκευή της διάδρασης, ενώ στο μάθημα Επικοινωνία Ανθρώπου-Υπολογιστή μας ενδιαφέρουν οι συσκευές διάδρασης)

**Comment by p18mili1** [comment]
@epidrome
Καλησπερα. Έχω δυο απορίες:
1) Για το συμμετοχικό περιεχόμενο πρέπει να κάνουμε καινούργιο fork  ή μπορούμε να χρησιμοποιήσουμε το repo για το βιβλίο που έχουμε ήδη φτιάξει για το μάθημα HCI;
2) Τα παραδοτέα πρέπει να έχουν και το Α1 και το Α2 (ή το Β1 και το Β2) ή ένα από τα Α1, Α2 (ή Β1,Β2);

**Comment by p15xiar** [comment]
@p18mili1
Καλησπερα.
Όσον αφορά την πρώτη απορία σου οι οδηγείες αναφέρουν ότι το pull request ειναι προαιρετικό οπότε σε περίπτωση που δεν θέλεις να διαγράφεις repos και να τα ξανακάνεις fork και να ξανακάνεις setup τα submodules μπορείς απλά να κάνεις δουλειά στα ίδια repos και να βαλεις απλα τα link τους μαζι με τα links απο τα netlify deploys στην αναφορά σου. Σε περίπτωση που θέλεις να κάνεις και pull request τότε δεν ξέρω.
Στο HCI που είχαμε επίσης 2 παραδοτέα συμμετοχικού περιεχομένου την πρώτη εβδομάδα παραδόθηκαν τα Α1 και Α2 και την επόμενη τα Β1 και Β2

**Comment by p18mili1** [comment]
p15xiar
Καλημέρα
Κατ' αρχάς ευχαριστω για την απόκριση. Σε σχέση με την πρώτη απορία μου και την απάντησή σου όμως κρατώ μόνο το ότι μπορώ να χρησιμοποιήσω το υπάρχον repo του βιβλίου και να προσθέσω σε αυτό. :-)
