### ISSUE TITLE
Εφαρμογή για ερωτήσεις πάνω στο video

### ISSUE THREAD

**Issue by sophia-ts** [courses-ionio/sw#918]
Η εφαρμογή είναι εντελώς σπασμένη. Προσπαθώ σχεδόν όλη μέρα με την άσκηση. Δεν μπορώ να κάνω pause, δεν μπορώ να επιστρέψω πίσω για να αλλάξω την απάντηση που έδωσα και αν κάνω κατά λάθος refresh τη σελίδα (κάτι το οποίο συνέβει) και πάω στο λεπτό που πρέπει να μου βγάλει την τέταρτη, για παράδειγμα, ερώτηση, μου βγάζει την πρώτη. Εξαρτάται ο βαθμός μας από αυτή την εργασία. Αφού παρουσίαζει τόσα πολλά προβλήματα, προτείνω να γίνουν οι ερωτήσεις μέσω google forms όπου στην αρχή μπορείτε να έχετε το url από το video στο youtube. Ή έστω, να μην προσμέτρηθούν στην τελική βαθμολογία τα βίντεο που παρουσιάζουν προβλήματα.

**Comment by Haki-Malai** [comment]
Εμένα ενώ πάτω το κουμπί submit, τίποτα δεν συμβένει. Είναι λογικό αυτό;

**Comment by epidrome** [comment]
η εφαρμογή δουλεύει μια χαρά, αρκεί να βλέπουμε το βίντεο γραμμικά χωρίς πολύ πλοήγηση, οπότε γίνεται εύθραστη, γιατί δεν έχει σχεδιαστεί να κάνει έλεγχο για κάθε πιθανό γεγονός-ενέργεια του χρήστη

οι ερωτήσεις και το δευτερόλεπτο εμφάνισης είναι πάντα διαθέσιμες δημόσια
https://github.com/pibook/questions/
