### ISSUE TITLE
Σχετικά με τις εργασίες ανάπτυξης του μαθήματος

### ISSUE THREAD

**Issue by ntouloumtzis** [courses-ionio/sw#920]
Θα ήθελα να συνεισφέρω σε μια εργασία ανάπτυξης και, συγκεκριμένα στο **[sitegr](https://github.com/ioniodi/sitegr/)**, αλλά δεν κατάλαβα αν χρειάζεται παραδοτέο ή κάποια δήλωση ενδιαφέροντος πριν την έναρξη του δεύτερου μαθήματος και, αν τελικά υπάρχουν deadlines. Έχω διαβάσει το README.md του αποθετηρίου της εργασίας, αλλά δεν γνωρίζω πως να ξεκινήσω. 
  Επιπλέον απορίες στο θέμα αυτό θα μπορούν να απαντηθούν, ίσως, στο επόμενο μάθημα;

**Comment by epidrome** [comment]
σύμφωνα με το αναλυτικό εβδομαδιαίο πρόγραμμα του μαθήματος είναι προαιρετική εργασία 

το πρώτο παραδοτέο της είναι την εβδομάδα:

> 3	Αίτημα ενσωμάτωσης στην ιστοσελίδα

περισσότερες πληροφορίες στις ώρες του μαθήματος!
